# Generated by Django 4.1.7 on 2023-02-17 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_app.modules.models.coworkers
import main_app.modules.models.panel


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoWorkers',
            fields=[
                ('code', models.CharField(default=main_app.modules.models.coworkers.key_generator, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('personal_commission', models.IntegerField(default=-1)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('code', models.CharField(default=main_app.modules.models.panel.key_generator, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='پنل من', max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.BigIntegerField()),
                ('description', models.TextField()),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('coworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coworkers')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.panel')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('commission', models.PositiveIntegerField()),
                ('up_lavel_commission', models.PositiveIntegerField()),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.panel')),
            ],
        ),
    ]
