# Generated by Django 4.1.7 on 2023-02-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_coworkers_user_remove_sellhistory_panel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellhistory',
            old_name='mount',
            new_name='amount',
        ),
    ]
