# Generated by Django 4.1.7 on 2023-02-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_coworkers_parent_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworkers',
            name='parent',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
