# Generated by Django 4.1.7 on 2023-02-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_coworkers_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='up_lavel_commission',
        ),
    ]
