# Generated by Django 4.1.7 on 2023-02-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_level_up_lavel_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='child_profits',
            field=models.BigIntegerField(default=0),
        ),
    ]
