# Generated by Django 4.1.7 on 2023-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_credit_child_profits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellhistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
