# Generated by Django 4.1.7 on 2023-02-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='number_of_child_sell',
            field=models.IntegerField(default=0),
        ),
    ]
