# Generated by Django 4.1.7 on 2023-02-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_credit_number_of_child_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
